export default ({
  GET_ACCOUNTS_SUCCESS: Symbol('GET_ACCOUNTS_SUCCESS'),
  GET_ACCOUNTS_ERROR: Symbol('GET_ACCOUNTS_ERROR'),
  ADD_ACCOUNT_SUCCESS: Symbol('ADD_ACCOUNT_SUCCESS'),
  ADD_ACCOUNT_ERROR: Symbol('ADD_ACCOUNT_ERROR'),
  DELETE_ACCOUNT_SUCCESS: Symbol('DELETE_ACCOUNT_SUCCESS'),
  DELETE_ACCOUNT_ERROR: Symbol('DELETE_ACCOUNT_ERROR'),
})